filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/filebeat/fiber_logs.json
    json.keys_under_root: true
    json.add_error_key: true

output.logstash:
  hosts: ["logstash:5044"]
